"""
티츄 게임 로직. 1단계: 카드·덱·상태 정의. 2단계: 준비 단계.
"""
from tichu.cards import Card, make_deck, shuffle_deck, card_points
from tichu.combo_info import ComboInfo, evaluate_combo, can_beat
from tichu.state import GameState, RoundState, init_state, new_round_state, team_id
from tichu.prepare import (
    sort_hand,
    deal_initial_8,
    deal_remaining_6,
    apply_exchange,
    set_leader_by_mahjong,
    run_prepare_phase,
)
from tichu.game_loop import is_game_over, run_game, finalize_round
from tichu.mahjong_call import (
    can_declare_mahjong_call,
    set_mahjong_call,
    clear_mahjong_call,
    hand_can_possibly_match_mahjong_call,
    find_legal_plays,
    find_legal_plays_matching_call,
    selection_satisfies_mahjong_call,
    must_follow_mahjong_call,
    can_pass_with_mahjong_call,
)
from tichu.scoring import calculate_round_score_deltas, apply_round_scores
from tichu.trick import (
    can_declare_small_tichu,
    declare_small_tichu,
    start_trick,
    get_next_active_player,
    get_legal_plays,
    can_player_pass,
    is_double_victory,
    is_round_over,
    get_round_end_reason,
    play_cards,
    pass_turn,
    resolve_trick_end,
)
from tichu.engine import (
    ApplyExchangeAction,
    DeclareGrandTichuAction,
    DeclareSmallTichuAction,
    EngineSnapshot,
    EngineState,
    PassTurnAction,
    PlayCardsAction,
    PHASE_AWAIT_EXCHANGE,
    PHASE_AWAIT_GRAND_TICHU,
    PHASE_AWAIT_TURN_ACTION,
    PHASE_GAME_FINISHED,
    PHASE_IDLE,
    PHASE_ROUND_FINISHED,
    can_submit_action,
    create_engine,
    get_engine_snapshot,
    start_game,
    start_round,
    submit_action,
)

__all__ = [
    "Card",
    "make_deck",
    "shuffle_deck",
    "card_points",
    "ComboInfo",
    "evaluate_combo",
    "can_beat",
    "GameState",
    "RoundState",
    "init_state",
    "new_round_state",
    "team_id",
    "sort_hand",
    "deal_initial_8",
    "deal_remaining_6",
    "apply_exchange",
    "set_leader_by_mahjong",
    "run_prepare_phase",
    "is_game_over",
    "run_game",
    "finalize_round",
    "can_declare_mahjong_call",
    "set_mahjong_call",
    "clear_mahjong_call",
    "hand_can_possibly_match_mahjong_call",
    "find_legal_plays",
    "find_legal_plays_matching_call",
    "selection_satisfies_mahjong_call",
    "must_follow_mahjong_call",
    "can_pass_with_mahjong_call",
    "calculate_round_score_deltas",
    "apply_round_scores",
    "can_declare_small_tichu",
    "declare_small_tichu",
    "start_trick",
    "get_next_active_player",
    "get_legal_plays",
    "can_player_pass",
    "is_double_victory",
    "is_round_over",
    "get_round_end_reason",
    "play_cards",
    "pass_turn",
    "resolve_trick_end",
    "ApplyExchangeAction",
    "DeclareGrandTichuAction",
    "DeclareSmallTichuAction",
    "EngineSnapshot",
    "EngineState",
    "PassTurnAction",
    "PlayCardsAction",
    "PHASE_AWAIT_EXCHANGE",
    "PHASE_AWAIT_GRAND_TICHU",
    "PHASE_AWAIT_TURN_ACTION",
    "PHASE_GAME_FINISHED",
    "PHASE_IDLE",
    "PHASE_ROUND_FINISHED",
    "can_submit_action",
    "create_engine",
    "get_engine_snapshot",
    "start_game",
    "start_round",
    "submit_action",
]
